### ISSUE TITLE
Updating a model via constructor causes a Vuex error

### ISSUE THREAD

**Issue by Palivonas** [feathers-plus/feathers-vuex#206] opened 2019-02-28 11:17 UTC
As of v1.7.0, creating a new record in the store works fine like so:
```js
new $nuxt.$FeathersVuex.User({
  "id": "doug",
  "name": "Doug Bowser",
});
```
A new record is added to the store, reactivity seems to work fine. Calling the constructor with exact same data again also causes no errors. However, calling the constructor with an existing id and modified data causes a Vuex error:
```js
new $nuxt.$FeathersVuex.User({
  "id": "doug",
  "name": "Doug Bowsette",
});
```
```
vue.runtime.esm.js:1887 Error: [vuex] do not mutate vuex store state outside mutation handlers.
    at assert (vuex.esm.js:87)
    at Vue.store._vm.$watch.deep (vuex.esm.js:763)
    at Watcher.run (vue.runtime.esm.js:4529)
    at Watcher.update (vue.runtime.esm.js:4503)
    at Dep.notify (vue.runtime.esm.js:730)
    at FeathersVuexModel.reactiveSetter [as some] (vue.runtime.esm.js:1055)
    at utils.js:276
    at Array.forEach (<anonymous>)
    at updateOriginal (utils.js:250)
    at new FeathersVuexModel (model.js:44)
```

Using `store.dispatch('orders/addOrUpdate', newRecord)` does not have the same issue, however.

**Comment by NickBolles** [comment] 2019-02-28 14:10
Possibly similar to my other issue https://github.com/feathers-plus/feathers-vuex/issues/195

**Comment by Palivonas** [comment] 2019-02-28 16:36
> Possibly similar to my other issue #195

#195 is caused by records not being FeathersVuexModel instances in some cases. This issue is about updating records in Vuex store. I'm afraid I'm missing the connection, could you elaborate please?

**Comment by NickBolles** [comment] 2019-02-28 18:31
Both are related to getting records from the Vuex store.

In both cases, calling New on a record not on the store works fine. But the second time (with an ID) it doesn't. 

Similar reproduction steps, not the same issue. But it's worth linking the issues together IMO.

**Comment by marshallswain** [comment] 2019-03-20 17:32
thanks @NickBolles and @Palivonas!  I've had my head buried in a project for a while.  We definitely should be calling a mutation to make the updates.

**Comment by marshallswain** [comment] 2019-04-30 22:46
@NickBolles @Palivonas I believe the pre-release fixes this issue.  It's in the `typescript` branch.

**Comment by marshallswain** [comment] 2019-09-24 19:45
I'm going to close this since it's fixed in the pre-release.

**Closed by marshallswain** 2019-09-24 19:45 UTC
Labels: Fixed in next release, bug
