### ISSUE TITLE
Creating multiple records using service.create(data) with an array yields: no id error

### ISSUE THREAD

**Issue by tommygarces** [feathers-plus/feathers-vuex#61] opened 2017-10-18 20:39 UTC
When dispatching create action on a service with an array of multiple objects as data:
```
var data = [
{name: 'index', permissions: 'guest'},
{name: 'about', permissions: 'guest'},
{name: 'admin', permissions: 'superuser'}
]
store.dispatch('/pages/create', data)
```
, the following error appears:
```
Error: No id found for item. Do you need to customize the `idField`?
```
The data is succesfully added to the database. The problem is when the promise is returned to the action and sent to the addOrUpdate action.

Upon analyzing the create action in **src/service-module/actions.js**, it seems that the error is produced by treating the response of the service.create(data) as a single object and passing that to addOrUpdate instead of addOrUpdateList:
```
create ({ commit, dispatch }, data) {
      commit('setCreatePending')

      return service.create(data)
        .then(item => {
          dispatch('addOrUpdate', item)
          commit('setCurrent', item)
          commit('unsetCreatePending')
          return item
        })
        .catch(error => {
          commit('setCreateError', error)
          commit('unsetCreatePending')
          return Promise.reject(error)
        })
}
```

**Comment by marshallswain** [comment] 2017-10-20 14:13
Ah, yes.  I haven't handled array responses.  Thank you for spotting this.  I'll probably be able to fix this over the weekend, unless you have the bandwidth to submit a PR.  🙏

**Comment by fionagithub** [comment] 2017-11-17 11:46
+1

**Comment by fionagithub** [comment] 2017-11-21 03:14
what should i do to filter that progame catch this error

**Comment by bobcat1** [comment] 2018-01-19 16:12
Is there any news on this? Based on @tommygarces digging, I've been trying to get it to call addOrUpdateList when the response is an array, but it seems I'm missing something else to make it work as intended.

**Comment by Torge** [comment] 2018-01-31 16:22
The only Problem I see in this is that 'addOrUpdateList' assumes the provided array is the complete list and will remove all items from the store that are not included in the provided array if autoRemove is turned on.
This is what you expect to happen if you dispatch 'find', but unsuitable if you dispatch an bulk request.

There should maybe be two different actions for bulk requests and find.

**Comment by bobcat1** [comment] 2018-01-31 19:39
@Torge thanks for the suggestion, however even when doing it that way, the `id = null` for the returned items.

**Comment by Torge** [comment] 2018-02-01 07:59
@bobcat1 sorry i looked at your original issue just now, but it seems like this issue is dealing with the problem of not handeling the response of bulk 'create' as specified here [https://docs.feathersjs.com/api/services#createdata-params](url)
`data may also be an array.`

Your Problem seems to be, not having an unique single id.

**Comment by bobcat1** [comment] 2018-02-01 14:53
@Torge This issue is not related to #67. 

My use case in relation to this specific issue is:
I'm trying to add an array of items, and then I need to use the IDs returned to add more items, based on the IDs returned from the first array. It's just that all IDs are `null` when returned. So my workaround right now is to make a `find` call after they have all been added. That way I get all the IDs, and can use them to add the rest of my data.

**Comment by marshallswain** [comment] 2018-03-30 13:40
This is fixed in the latest pre-release.  `npm i feathers-vuex@pre`, and it will be included in the next minor version.

**Closed by marshallswain** 2018-03-30 13:40 UTC
