### ISSUE TITLE
Update Pagination After Create / Remove

### ISSUE THREAD

**Issue by Mattchewone** [feathers-plus/feathers-vuex#75] opened 2017-12-07 19:35 UTC
Once a create has happened and doing a check on the store `pagination` object this does not reflect the newest addition.

I am using the `pagination.default.total` in order to keep a pagination component up to date with how many items and how many pages needs to be displayed.

**Comment by marshallswain** [comment] 2017-12-07 19:44
```
We’ll have to run the newly-created item through the sifter with each query to see if it matched.

matt_c [12:38 PM] 
Can’t it just update the `pagination.default.total`?


marshall 
[12:38 PM] 
The pagination.default will have a matching query, though.
So it can’t just update it.
pagination data is based on the query.

matt_c [12:38 PM] 
Once I hit the 10 limit, the main window that was adding updated. but the other window didn’t show the second page number
Ah I see

marshall [12:38 PM] 
Unless you query with {}
To get the entire set.

matt_c [12:38 PM] 
You are right

marshall 
[12:38 PM] 
I’m actually storing the query with each pagination request, I believe.
So it’s do-able.
But we do have to run the item through the sifter with each pagination’s query to know if we should increment the total or not.
```

**Comment by Mattchewone** [comment] 2018-03-01 13:46
@marshallswain Should this https://github.com/feathers-plus/feathers-vuex/blob/master/src/service-module/getters.js#L15 not be based of the `response.total` rather than the total that is presently in the store? If we set `$limit: 10` and there are `50` records the store total from the getter will be `10`

**Comment by marshallswain** [comment] 2018-03-01 14:40
Nope.  This is the response for what's in the local store.  They operate independently.  If you require the numbers from the server, use the action and pass a `qid` to track the pagination data.

**Comment by marshallswain** [comment] 2019-09-24 20:21
I'm going to close this since I don't have an immediate need for the fix.  The solution/workaround to the issue is to switch to the `makeFindMixin` and perform a find request right after create or remove.

**Closed by marshallswain** 2019-09-24 20:21 UTC
Labels: enhancement
