### ISSUE TITLE
InstanceDefaults not being respected on patch or save

### ISSUE THREAD

**Issue by pbpraha** [feathers-plus/feathers-vuex#228] opened 2019-06-10 15:59 UTC
### Steps to reproduce
Use patch or save to update a record that contains a field of type Date.

### Expected behavior
When the updated record is returned from the server and integrated into the store, the Date field is now a String and cannot be queried using e.g. {$gt:somedate}

### Actual behavior
When integrating the update, the store should honour the Date data type

### System configuration
VM Centos7, node 12.3.1, feathers-vuex, vuetify

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
feathers-vuex 1.7.0

**NodeJS version**:
node 12.3.1

**Operating System**:
VM Centos7

**Browser Version**:
all

**React Native Version**:

**Module Loader**:
webpack

a little gif of the problem:
https://imgur.com/a/Qlmg6Nv

**Comment by marshallswain** [comment] 2019-06-10 17:15
I incorrectly thought that your issue was in the API server, but since you've confirmed in the referenced PR #119 that the issue is with the local store, we can track this down easier.  I suspect that your issue is fixed in the current prerelease of feathers-vuex@pre, but I'm not certain about it, yet.  The prerelease is the same as the typescript branch.  If you try to upgrade, you'll need to modify some of your code  (it's a major release).

**Comment by pbpraha** [comment] 2019-06-10 17:23
Super, thanks.

There is no real urgency to this for me, i'm currently evaluating if the framework can be used to replace our aged and creaking (largely single user) react app. 
So far it looks promising but this issue totally stumped me.

here's my use case: (for one tiny corner of our application)
User has a list of todos - sometimes 300+ or so (their business runs on todo's...)
The list is actually displayed as six lists:
- Today's Todos
- Todos for Later
- Overdue Todos
- Undated Todos
- Completed Todos (to check they were really done ...)
- Todos Created for Other Staff.

each list queries the API to get it's sub-set of the todo list.

Patching any field on a todo means that it instantly disappears from e.g. "Todos for Later" - because the store query cannot now find that todo by the due date (which, since the record-patch, is now a date string)

**Comment by marshallswain** [comment] 2019-06-10 17:25
Perfect.  I have an app coming up that will require this to be fixed, too, so this was perfect timing to bring this up.

**Comment by marshallswain** [comment] 2019-06-27 17:44
This is fixed in the typescript branch.  You can try it out with `npm i feathers-vuex@2.0.0-pre.45`.

**Comment by pbpraha** [comment] 2019-06-28 12:02
Thanks Marshall.

Um, i'm embarrassed to say that i've never used typescript - I do all my coding in plain JS. 
Are the two compatible ? i.e can I use this branch with my existing node-express-feathers-vuew-vuex-vuetify setup or will it puke?

Cheers
Paul

**Comment by marshallswain** [comment] 2019-06-28 13:24
@pbpraha You don't need to know TypeScript.  I compile to ES6 for publishing.

That said, it's a major release, so there's some code you'd need to modify: https://github.com/feathers-plus/feathers-vuex/pull/216

**Comment by marshallswain** [comment] 2019-07-21 07:45
The fix for this is now in place and tested in the pre-release.   It's accomplished using the setupInstance method on a Model class.  To try it out, you have to specifically install the latest version:  

`npm i feathers-vuex@2.0.0-pre.65` or `yarn add feathers-vuex@2.0.0-pre.65`

```
class Letter extends BaseModel {
    public constructor(data?, options?) {
      super(data, options)
    }
    public static modelName = 'Letter'
    public static instanceDefaults(data, { models, store }) {
      return {
        to: '',
        from: ''
      }
    }
    public static setupInstance(data, { models }) {
      if (typeof data.createdAt === 'string') {
        data.createdAt = new Date(data.createdAt) // just assuming the date is formatted correctly ;)
      }
      return data
    }
}
```

**Comment by marshallswain** [comment] 2019-09-24 19:45
I'm going to close this since it's fixed in the pre-release.

**Closed by marshallswain** 2019-09-24 19:45 UTC
Labels: Fixed in next release, major
