### ISSUE TITLE
$elemMatch causes an error since v1.7.0-pre.39

### ISSUE THREAD

**Issue by Palivonas** [feathers-plus/feathers-vuex#193] opened 2019-01-19 13:24 UTC
This seems to have started since v1.7.0-pre.39 (which is not published on npm, by the way)

### Steps to reproduce

Try using $elemMatch in store query.
Repo/commit to reproduce: https://github.com/Palivonas/feathers-vuex-bug-reproduction/commit/2659170e2c0d80a8470d4998bf504cb9e279b944

### Expected behavior
It does not fail

### Actual behavior
Fails with error `"BadRequest: Invalid query parameter $elemMatch"`. This has nothing to do with backend - the error can happen without making any network requests. Something to do with Sift maybe?

**Module versions**:
`"feathers-vuex": "1.7.0-pre.47"`

**Browser Version**:
Chrome

**Comment by marshallswain** [comment] 2019-01-25 17:15
Uggh.  This is caused by the new feathers/db-commons package.  It gave me a huge headache, yesterday.  I'll see if I can make a fix for this.  The getter will have to be updated.

**Comment by marshallswain** [comment] 2019-01-25 17:43
This is fixed in `feathers-vuex@1.7.0-pre.52`.  Thanks for the bug report.

The `$elemMatch` operator is now officially supported, with its own test: 

https://github.com/feathers-plus/feathers-vuex/commit/58a75a5407dc73a5e9781e266b92bfd503e9bcfa

**Closed by marshallswain** 2019-01-25 17:43 UTC
