### ISSUE TITLE
Infinite Loop in InstanceDefaults when using Models.service.get(id)

### ISSUE THREAD

**Issue by kshitizshankar** [feathers-plus/feathers-vuex#241] opened 2019-08-08 16:26 UTC
### Steps to reproduce
Hi, 
I am using the sample code from the docs  - 

```
instanceDefaults (data, { store, Model, Models }) {
        return {
          description: '',
          isComplete: false,
          userId: null,
          get user () {
            if (this.userId) {
              const user = Models.User.getFromStore(this.userId)

              // Fetch the User record if we don't already have it
              if (!user) {
                Models.User.get(this.userId)
              }

              return user
            } else {
              return null
            }
          }
        }
```

When the userId doesn't exist on the server (and sometimes even when it does - still trying to figure out where the infinite loop happens in that case), it goes into an infinite loop.

I also checked if this was related to https://github.com/feathers-plus/feathers-vuex/issues/207 but something else seems to be happening in this case. 

I am quite new to feathers-vuex and trying to figure out if it's a bug or if I did something wrong.

### System configuration
**Feathers-vuex version**: v1.7.0
**NodeJS version**: v11.6.0

Thanks!

**Comment by marshallswain** [comment] 2019-08-08 19:54
@kshitizshankar thanks for filing this.  I actually just ran into this exact same issue, yesterday.  I believe that the issue is caused by the way that Vue tracks and re-runs dependencies.  I wasn't able to come up with a solution other than to move the API request (`Models.User.get()`) outside of the getter.

**Comment by marshallswain** [comment] 2019-08-08 19:55
This issue definitely deserves more research to see if there's a decent workaround.

**Comment by kshitizshankar** [comment] 2019-08-09 06:25
Thanks for the reply! I wasn't sure if there were any workarounds for this or not, so ended up removing the get requests from instance defaults as well. 

It might be a good idea to mention it in docs till we find a solution, given it will crash the app/browser when it happens.

**Comment by marshallswain** [comment] 2019-09-24 20:19
I'm closing this issue since I've added it to the bottom of the new documentation, to eventually be merged into real docs.

**Closed by marshallswain** 2019-09-24 20:19 UTC
Labels: documentation
